SELECT * FROM empleados;
SELECT * FROM departamentos;
SELECT nombre_depto FROM departamentos ORDER BY nombre_depto ASC;
SELECT nombre, sal_emp FROM empleados;
SELECT comision_emp FROM empleados ORDER BY comision_emp DESC;
SELECT * FROM empleados WHERE cargo_emp = "Secretaria";
SELECT * FROM empleados WHERE cargo_emp = "VENDEDOR" order by nombre asc;
select nombre,cargo_emp from empleados order by sal_emp desc;
select nombre_jefe_depto "nombre" from departamentos where ciudad = "ciudad real";
select nombre "Nombre", cargo_emp "Cargo" from empleados;
select sal_emp as "Salario", comision_emp as "Comision" from empleados where id_depto = 2000 order by comision_emp ASC;
select nombre as "Nombre", sal_emp+comision_emp+500 as "Total a pagar" from empleados where id_depto = 3000 order by nombre asc;
SELECT * FROM empleados WHERE nombre LIKE "j%";
select nombre "Nombre", sal_emp "Salario", comision_emp "Comision", sal_emp+comision_emp "Salario Total" from empleados where comision_emp >1000;
select nombre "Nombre", sal_emp "Salario", comision_emp "Comision", sal_emp+comision_emp "Salario Total" from empleados where comision_emp = 0;
select * from empleados where comision_emp>sal_emp;
select * from empleados where comision_emp <= (sal_emp*30)/100;
select * from empleados where nombre NOT like "%ma%";
select nombre_jefe_depto from departamentos where nombre_depto like "ventas" or nombre_depto like "investigacion" or nombre_depto like "mantenimiento";
select nombre_jefe_depto from departamentos where nombre_depto not like "ventas" and nombre_depto not like "investigacion" and nombre_depto not like "mantenimiento";
SELECT nombre, cargo_emp, sal_emp FROM empleados ORDER BY sal_emp DESC LIMIT 1;
SELECT * FROM empleados ORDER BY nombre DESC LIMIT 1;
SELECT MAX(sal_emp) AS salario_maximo,MIN(sal_emp) AS salario_minimo,MAX(sal_emp) - MIN(sal_emp) AS diferencia_salarios FROM empleados;
SELECT id_depto, AVG(sal_emp) AS salario_promedio FROM empleados GROUP BY id_depto; SELECT d.nombre_depto, AVG(e.sal_emp) AS salario_promedio FROM empleados e JOIN departamentos d ON e.id_depto = d.id_depto GROUP BY d.id_depto;
SELECT id_depto, COUNT(*) AS numero_empleados FROM empleados GROUP BY id_depto HAVING COUNT(*) > 3;
SELECT id_depto, COUNT(*) AS numero_empleados FROM empleados GROUP BY id_depto HAVING COUNT(*) = 0;
SELECT nombre, sal_emp, id_depto FROM empleados WHERE sal_emp >= (SELECT AVG(sal_emp) FROM empleados) ORDER BY id_depto;